<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="5" total="10" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-11-12T18:46:39 IST" name="Techniques" finished-at="2022-11-12T18:46:39 IST" duration-ms="50">
    <groups>
      <group name="SmokeTest">
        <method signature="Eleven.eleven()[pri:0, instance:Test.Eleven@20f5239f]" name="eleven" class="Test.Eleven"/>
        <method signature="Eleven.thirteen()[pri:0, instance:Test.Eleven@20f5239f]" name="thirteen" class="Test.Eleven"/>
        <method signature="One.two()[pri:0, instance:Test.One@cad498c]" name="two" class="Test.One"/>
        <method signature="ThirtyOne.thirtyOne()[pri:0, instance:Test.ThirtyOne@932bc4a]" name="thirtyOne" class="Test.ThirtyOne"/>
        <method signature="ThirtyOne.thirtyTwo()[pri:0, instance:Test.ThirtyOne@932bc4a]" name="thirtyTwo" class="Test.ThirtyOne"/>
      </group> <!-- SmokeTest -->
    </groups>
    <test started-at="2022-11-12T18:46:39 IST" name="SmokeTest" finished-at="2022-11-12T18:46:39 IST" duration-ms="50">
      <class name="Test.ThirtyOne">
        <test-method signature="thirtyOne()[pri:0, instance:Test.ThirtyOne@932bc4a]" started-at="2022-11-12T18:46:39 IST" name="thirtyOne" finished-at="2022-11-12T18:46:39 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- thirtyOne -->
        <test-method signature="thirtyTwo()[pri:0, instance:Test.ThirtyOne@932bc4a]" started-at="2022-11-12T18:46:39 IST" name="thirtyTwo" finished-at="2022-11-12T18:46:39 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- thirtyTwo -->
      </class> <!-- Test.ThirtyOne -->
      <class name="Test.One">
        <test-method signature="two()[pri:0, instance:Test.One@cad498c]" started-at="2022-11-12T18:46:39 IST" name="two" finished-at="2022-11-12T18:46:39 IST" duration-ms="7" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at Test.One.two(One.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- two -->
      </class> <!-- Test.One -->
      <class name="Test.Eleven">
        <test-method signature="eleven()[pri:0, instance:Test.Eleven@20f5239f]" started-at="2022-11-12T18:46:39 IST" name="eleven" finished-at="2022-11-12T18:46:39 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- eleven -->
        <test-method signature="thirteen()[pri:0, instance:Test.Eleven@20f5239f]" started-at="2022-11-12T18:46:39 IST" name="thirteen" finished-at="2022-11-12T18:46:39 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- thirteen -->
      </class> <!-- Test.Eleven -->
    </test> <!-- SmokeTest -->
  </suite> <!-- Techniques -->
</testng-results>
